### ISSUE TITLE
디자인 패턴 정리 추가

### ISSUE THREAD

**Issue by huisam** [huisam/JinLearnedList#6]
* Decorator Pattern
* Bridge Pattern
* Proxy Pattern

**Comment by huisam** [comment]
모든 항목 공부 끝~! 👍

**Comment by huisam** [comment]
모든 항목 공부 끝~! 👍

**Comment by jjeda** [comment]
이제 AOP 공부하시면 되겠네요^^

**Comment by huisam** [comment]
@jjeda 벌써 AOP까지 끝내셨다구요?ㄷㄷ 그저 빛..
